### ISSUE TITLE
Doesn't support CLI profiles

### ISSUE THREAD

**Issue by evilneuro** [tilfin/aws-iam-policy-tool#11]
There does not seem to be a way to select a specific CLI profile, as defined in `~/.aws/credentials` and/or `~/.aws/config`.

Attempting to override by manually setting the `AWS_DEFAULT_PROFILE` environment variable to the desired CLI profile name does nothing; whatever is defined as `default` in the CLI config is used regardless.

**Comment by tilfin** [comment]
@evilneuro Use `AWS_PROFILE=yourprofile`

**Comment by evilneuro** [comment]
D'oh. Works as expected. Apologies, and thanks!
